default:
  adapter: postgresql
  encoding: unicode
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
development:
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV['DB_HOST'] %>"
  port: "<%= ENV['DB_PORT'] %>"
  username: "<%= ENV['DB_USER'] %>"
  password: "<%= ENV['DB_PASSWORD'] %>"
  database: "<%= ENV['DB_NAME'] %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
production:
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV['DB_HOST'] %>"
  port: "<%= ENV['DB_PORT'] %>"
  username: "<%= ENV['DB_USER'] %>"
  password: "<%= ENV['DB_PASSWORD'] %>"
  database: "<%= ENV['DB_NAME'] %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: patential_portal_test
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
