# Generated by the protocol buffer compiler. DO NOT EDIT!
# Source: go/svc/patent/proto/service/service.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service.proto", :syntax => :proto3) do
    add_message "patent.Patent" do
      optional :id, :string, 1
      optional :application_number, :string, 2
      optional :application_kind, :string, 3
      optional :grant_date, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "patent.ListPatentsRequest" do
      optional :pagination, :message, 1, "patent.Pagination"
    end
    add_message "patent.ListPatentsResponse" do
      repeated :patents, :message, 1, "patent.Patent"
    end
    add_message "patent.Pagination" do
      optional :offset, :int32, 1
      optional :limit, :int32, 2
    end
  end
end

module Patent
  Patent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patent.Patent").msgclass
  ListPatentsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patent.ListPatentsRequest").msgclass
  ListPatentsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patent.ListPatentsResponse").msgclass
  Pagination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patent.Pagination").msgclass
end
